#!/usr/bin/env bash
# A bash script that displays:
#	"To infinity and beyond" indefinitely
#	With a "sleep 2" in between each iteration
# 	"I am invincible!!!" when receiving SIGTERM signal

while ((1)); do
	trap 'echo "I am invincible"' SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
