#!/usr/bin/env bash
# Displays numbers from 1 to 100
#	Displays "FizzBuzz" when the number is a multiple of 3 and 5
#	Displays "Fizz" when the number is a multiple of 3
# 	Displays "Buzz" when the number is a multiple of 5
# 	Otherwise, displays the number



