#!/usr/bin/env bash
# This script displays "Best School" 9 times and "hi"

i=0
while (("$i" < 10)); do
	if (("$i" == 8)); then
		echo "Hi"
		((i=i+1))
		continue
	fi
	echo "Best School"
	((i=i+1))
done
